{% set name = "magic-class" %}
{% set version = "0.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3e7bc5d2223579dbfb42a9b7a293c027e5f3419ffe2841e9ec7cd8354ffbd920

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - docstring_parser >=0.15
    - macro-kit >=0.4.6
    - magicgui >=0.8.0
    - matplotlib-base  # Imported but not declared in requirements
    - numpy
    - psygnal >=0.9.0
    - python >={{ python_min }}
    - qt-command-palette  # Imported but not declared in requirements
    - qtpy >=1.10.0
    - superqt >=0.6.1
    - typing-extensions >=4.5.0
    # Optional extensions
    # - dask
    # - napari
    # - polars
    # - pyqtgraph
    # - qtconsole
    # - vedo
    # - vispy
    # - vtk

test:
  imports:
    - magicclass
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/magic-class
  summary: Generate multifunctional GUIs from classes
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/hanjinliu/magic-class

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinliu
