{% set name = "magic-class" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/magic-class-{{ version }}.tar.gz
  sha256: 112c486d3afa9f43edc5d44707b1b45b14dd9eafcbedbbc3d2280c43f8cc8d63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - macro-kit >=0.3.5
    - magicgui >=0.3.4
    - python >=3.8
    - qtpy >=1.10.0

test:
  imports:
    - magicclass
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/hanjinliu/magic-class
  summary: Generate multifunctional GUIs from classes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinliu
